3.0.5

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,16 +3,16 @@ if (( $EUID != 0 )); then
     printf "\n-----Sorry! Run with root privilege\n\n"
     exit 1
 fi
-cd "$(dirname "$BASH_SOURCE")"
+cd "$(dirname "$BASH_SOURCE")" || { echo failed; exit 1; }
 ## installing manual
 mkdir -p /usr/share/man/man1/
-cp ./rnm.1 /usr/share/man/man1/rnm.1
+cp ./rnm.1.gz /usr/share/man/man1/rnm.1.gz || echo "Manual install failed"
 ## copying binary
 if [ "$(uname -m)" = "x86_64" ];then
-cd bin/x64
+cd bin/x64 || { echo failed; exit 1; }
 else
-cd bin/x32
+cd bin/x32 || { echo failed; exit 1; }
 fi
-cp ./rnm /usr/bin/rnm
+cp ./rnm /usr/bin/rnm || { echo failed; exit 1; }
 chmod 755 /usr/bin/rnm
 echo "***** Success *****"
