2.0.1

diff --git a/rnm b/rnm
--- a/rnm
+++ b/rnm
@@ -4,7 +4,7 @@ shopt -s extglob
 
 ##########################################################################################################
 projectName="rnm"
-version="2.0.0"
+version="2.0.1"
 authorName="Jahidul Hamid"
 authorEmail="jahidulhamid@yahoo.com"
 bugReportURL="http://github.com/neurobin/$projectName/issues"
@@ -96,6 +96,8 @@ Name String       : A string which is parsed to create name for new files.
      /idr/ in name string will be replaced with reserved directory index
      /n/ in name string will be replaced with filename without extention.
      /fn/ in name string will be replaced with full name of the files.
+     /smn/ in name string will be replaced with Sed Modified Name.
+     /rn/ in name string will be replaced with Sed Modified Name.
      /l/ in name string will be replaced with line number from list file.
      /dc/ in name string will be replaced with directory count
      /-i/ in name string will be replaced with inverse index.
@@ -112,6 +114,26 @@ Search String     : A string that is used to search for files with matching
 Index Field Length: An integer value defining the field length of index.
                     empty field will be filled with 0's. For example, if
                     the value is 3, then index will be 001, 002, 003, etc..
+                    
+Sed Modified Name : The name can be modified at runtime using the default
+                    sed tool available in Linux system. You can insert sed
+                    script in the form /search_string/replace_string/modifier;
+                    
+                    For example: '/video/Episode/gi;' will replace every instances
+                    of 'video' with 'Episode' in the name of the file found (or the name 
+                    taken from Name String File).
+                    
+                    The format must be of :
+                    /search_string/replace_string/modifier;
+                    
+                    Two modifiers are avalilable: g and i.
+                    g stands for global. Replaces every instances of match found.
+                    i stands case insensitive search.
+                    
+                    This replaced modified name is available through Name String Rule: 
+                    /smn/ or /rn/ (stands for replaced name)
+                    
+                    Note that sed basic regex mode is used to do this job.
 "
 ##########################################################################################################
 ###### Global Variables ###########
@@ -131,7 +153,9 @@ errorlog="$logdir/errors.log"
 outlog="$logdir/out.log"
 renamedfilelog="$logdir/rfl.log.tmp"
 rnmfilelog="$logdir/rfl.log"
-
+rname=""
+sedreg="/[^/]*/[^/]*/[gi]{0,2}\;"
+SedScript=""
 
 
 quiet=false
@@ -237,6 +261,31 @@ chkPath(){
 return 0
 
 }
+
+
+applySedScriptOnName(){
+sedscript="$1";fname="$2"
+
+echo "$(echo "$fname" |sed "$sedscript"  2>/dev/null || { echo "$(echo "E: Syntax error in Name String." | tee -a /dev/stderr )" "....@$(date)" |tee -a "$errorlog" >/dev/null; exit 1; })"
+[[ $? != "0" ]] && return 1;
+}
+
+getSedScript(){
+IFS=$'\n' sedscripts=($(echo "$1" |grep -o "/[^/]*/[^/]*/[gi]\{0,2\}[;]"))
+#echo "$sedscript" |sed 's:^/:s/:g'
+for((i=0;i<"${#sedscripts[@]}";i++));do
+#script="${sedscripts[$i]}"
+#search="$(echo "$script" |sed 's:^/\([^/]*\)/.*:\1:')"
+#search="$(echo "$search" |sed 's:[^^]:[&]:g; s:\^:\\^:g')"
+#replace="$(echo "$script" |sed 's:^/[^/]*/\([^/]*\).*:\1:')"
+#mod="$(echo "$script" |sed 's:^/[^/]*/[^/]*/\([gi]\{0,2\}\).*:\1:')"
+sedscripts[$i]="s${sedscripts[$i]}"
+done
+echo "$(echo "${sedscripts[@]}" |tr -d '\n' )"
+}
+
+
+
 
 ##########################################################################################################
 ########################################### Opt Parse ####################################################
@@ -497,6 +546,15 @@ if [[ $nameStringFile != "" ]];then
   fi
 fi
 
+
+if [[ "$nameString" =~ $sedreg ]]; then
+    SedScript="$(getSedScript "$nameString")"
+    echo "$SedScript"
+fi
+
+
+
+
 [[ $searchString == "" ]] && { searchString=".*";bashSearchString=".*"; } || {
 if $sF;then 
     searchString="${searchString//\*/\\*}"
@@ -605,17 +663,27 @@ cd ..
             invdri1="$(printf "%0${ifl}d\n" $invdri)"
     fi
     fname="${file##*/}"
+
+        rname="${fname//\\/}"
+        if [[ "$SedScript" != "" ]]; then
+            rname="$(echo "$fname" |sed "$SedScript"  2>/dev/null || { echo "$(echo "E: Syntax error in Name String." | tee -a /dev/stderr )" "....@$(date)" |tee -a "$errorlog" >/dev/null; exit 1; })"
+            if [[ $? != "0" ]];then exit 2;fi
+            nameString="$(echo "$nameString" |sed "s:/[^/]*/[^/]*/[gi]\{0,2\}[;]::g")"
+        fi
+    
     fname="${fname//\\/}"
     fnamewe="${fname%.*}"
-    name="$nameString"
-    [[ $nameString == "" ]] && name="$fname"
-    name="${name//\/n\//$fnamewe}"
-    name="${name//\/fn\//$fname}"
-    name="${name//\/idr\//$dri1}"
-    name="${name//\/id\//$di1}"
-    name="${name//\/ir\//$ir1}"
-    name="${name//\/i\//$index}"
-    name="${name//\/dc\//$dc}"
+        name="$nameString"
+        [[ $nameString == "" ]] && name="$fname"
+        name="${name//\/n\//$fnamewe}"
+        name="${name//\/fn\//$fname}"
+        name="${name//\/smn\//$rname}"
+        name="${name//\/rn\//$rname}"
+        name="${name//\/idr\//$dri1}"
+        name="${name//\/id\//$di1}"
+        name="${name//\/ir\//$ir1}"
+        name="${name//\/i\//$index}"
+        name="${name//\/dc\//$dc}"
         name="${name//\/-i\//$invi1}"
         name="${name//\/-ir\//$invir1}"
         name="${name//\/-id\//$invdi1}"
@@ -691,8 +759,17 @@ cd ..
         
         (( $ln != $eln && $ln > 0 )) && fname="$(sed -n "${ln}s/.*/&/p" $nameStringFile || { echo "$(echo "E: sed error"  |tee /dev/stderr)" "    @$(date)" |tee -a  "$errorlog" >/dev/null;exit 35; })" || exit
         
-        fname="${fname//\\/}"
+        
         [[ $fname == "" ]] && { echo "$(echo "W: Name can not be empty, skipping..." |tee -a /dev/stderr)" "....@$(date)" |tee -a "$errorlog" >/dev/null; continue; }
+        
+
+        rname="${fname//\\/}"
+        if [[ "$SedScript" != "" ]]; then
+            rname="$(echo "$fname" |sed "$SedScript"  2>/dev/null || { echo "$(echo "E: Syntax error in Name String." | tee -a /dev/stderr )" "....@$(date)" |tee -a "$errorlog" >/dev/null; exit 1; })"
+            if [[ $? != "0" ]];then exit 2;fi
+            nameString="$(echo "$nameString" |sed "s:/[^/]*/[^/]*/[gi]\{0,2\}[;]::g")"
+        fi
+        fname="${fname//\\/}"
         fnamewe="${fname%.*}"
         index="$c"
         if="$ln"
@@ -720,6 +797,8 @@ cd ..
         [[ $nameString == "" ]] && name="$fname"
         name="${name//\/n\//$fnamewe}"
         name="${name//\/fn\//$fname}"
+        name="${name//\/smn\//$rname}"
+        name="${name//\/rn\//$rname}"
         name="${name//\/idr\//$dri1}"
         name="${name//\/id\//$di1}"
         name="${name//\/ir\//$ir1}"
@@ -821,12 +900,22 @@ else
             invdri1="$(printf "%0${ifl}d\n" $invdri)"
         fi
         fname="${file##*/}"
+        
+        rname="${fname//\\/}"
+        echo "$SedScript"
+        if [[ "$SedScript" != "" ]]; then
+            rname="$(echo "$fname" |sed "$SedScript"  2>/dev/null || { echo "$(echo "E: Syntax error in Name String." | tee -a /dev/stderr )" "....@$(date)" |tee -a "$errorlog" >/dev/null; exit 1; })"
+            if [[ $? != "0" ]];then exit 2;fi
+            nameString="$(echo "$nameString" |sed "s:/[^/]*/[^/]*/[gi]\{0,2\}[;]::g")"
+        fi
         fname="${fname//\\/}"
         fnamewe="${fname%.*}"
         name="$nameString"
         [[ $nameString == "" ]] && name="$fname"
         name="${name//\/n\//$fnamewe}"
         name="${name//\/fn\//$fname}"
+        name="${name//\/smn\//$rname}"
+        name="${name//\/rn\//$rname}"
         name="${name//\/idr\//$dri1}"
         name="${name//\/id\//$di1}"
         name="${name//\/ir\//$ir1}"
@@ -894,8 +983,19 @@ else
     
     if [[ "$nameStringFile" != "" ]]; then
         [[ $ln != $eln ]] && (( $ln > 0 )) && fname="$(sed -n "${ln}s/.*/&/p" $nameStringFile || { echo "$(echo "E: sed error"  |tee /dev/stderr)" "    @$(date)" |tee -a  "$errorlog";exit 46; })" || exit
+        [[ $fname == "" ]] && { echo "$(echo "W: Name can not be empty, skipping..." |tee -a /dev/stderr)" "....@$(date)" |tee -a "$errorlog" >/dev/null; continue; }
+        rname="${fname//\\/}"
+        if [[ "$SedScript" != "" ]]; then
+            rname="$(echo "$fname" |sed "$SedScript"  2>/dev/null || { echo "$(echo "E: Syntax error in Name String." | tee -a /dev/stderr )" "....@$(date)" |tee -a "$errorlog" >/dev/null; exit 1; })"
+            if [[ $? != "0" ]];then exit 2;fi
+            nameString="$(echo "$nameString" |sed "s:/[^/]*/[^/]*/[gi]\{0,2\}[;]::g")"
+        fi
+        
+        
         fname="${fname//\\/}"
         fnamewe="${fname%.*}"
+        
+
         
         index="$c"
         if="$ln"
@@ -923,6 +1023,8 @@ else
         [[ $nameString == "" ]] && name="$fname"
         name="${name//\/n\//$fnamewe}"
         name="${name//\/fn\//$fname}"
+        name="${name//\/smn\//$rname}"
+        name="${name//\/rn\//$rname}"
         
         name="${name//\/idr\//$dri1}"
         name="${name//\/id\//$di1}"
